import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Users, User, FileText, Home, RefreshCw, TrendingUp, AlertCircle, Clock } from "lucide-react";
import api from "@/services/api";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/context/LanguageContext";
import ReportPreview from "@/components/ReportPreview"; // Import the preview component

type DashboardStats = {
    citizens: number;
    families: number;
    servicesToday: number;
    pending: number;
};

import { useAuth } from "@/context/AuthContext";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function Dashboard() {
    const { user } = useAuth();
    const isAdmin = user?.role === 'Admin' || user?.role === 'admin';
    const { t } = useLanguage();
    const [stats, setStats] = useState<DashboardStats>({
        citizens: 0,
        families: 0,
        servicesToday: 0,
        pending: 0,
    });
    const [isLoading, setIsLoading] = useState(true);
    const [isGeneratingReport, setIsGeneratingReport] = useState(false);

    // New state for report preview
    const [reportData, setReportData] = useState<any[]>([]);
    const [isPreviewOpen, setIsPreviewOpen] = useState(false);

    useEffect(() => {
        const fetchStats = async () => {
            try {
                const res = await api.get("/dashboard");
                if (res.data) setStats(res.data);
            } catch (error) {
                console.error("Failed to load dashboard stats", error);
            } finally {
                setIsLoading(false);
            }
        };

        if (user) {
            fetchStats();
        }
    }, [user]);

    const handleGenerateReport = async () => {
        setIsGeneratingReport(true);
        try {
            const res = await api.get("/dashboard/report");
            setReportData(res.data); // Store data for preview
            setIsPreviewOpen(true); // Open preview modal
        } catch (error) {
            console.error("Failed to fetch report data", error);
            alert("Failed to fetch report data. Please try again.");
        } finally {
            setIsGeneratingReport(false);
        }
    };

    const handleDownloadPDF = () => {
        try {
            const doc = new jsPDF();

            // Add Header
            doc.setFontSize(18);
            doc.text(`${t('appName')} - Activity Report`, 14, 22);

            doc.setFontSize(11);
            doc.text(`Generated by: ${user?.name || 'Official'}`, 14, 30);
            doc.text(`Village: ${user?.villageContext?.villageName || 'N/A'}`, 14, 35);
            doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 40);

            // Add Table
            autoTable(doc, {
                startY: 50,
                head: [['Date', 'Type', 'Details', 'Status']],
                body: reportData.map((item: any) => [
                    new Date(item.date).toLocaleDateString(),
                    item.type,
                    item.details,
                    item.status
                ]),
            });

            doc.save("activity_report.pdf");
            setIsPreviewOpen(false); // Close preview after download
        } catch (error) {
            console.error("Failed to generate PDF", error);
            alert("Failed to generate PDF. Please try again.");
        }
    };

    return (
        <main className={`grid flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8 min-h-[calc(100vh-5rem)] ${isAdmin ? 'bg-transparent text-green-500 font-mono' : 'bg-muted/20'}`}>
            <ReportPreview
                isOpen={isPreviewOpen}
                onClose={() => setIsPreviewOpen(false)}
                data={reportData}
                onDownload={handleDownloadPDF}
            />
            <div className="flex items-center justify-between mt-6 mb-2">
                <div>
                    <h1 className={`text-3xl font-bold tracking-tight ${isAdmin ? 'text-green-500 uppercase' : 'text-primary'}`}>
                        {isAdmin ? 'GLOBAL_SYSTEM_METRICS' : (user?.villageContext?.villageName ? `${user.villageContext.villageName}` : t('dashboard'))}
                    </h1>
                    <p className={`mt-1 ${isAdmin ? 'text-green-600/70' : 'text-muted-foreground'}`}>
                        {isAdmin ? 'Real-time root data access across all nodes. Monitoring active.' : (user?.villageContext?.villageName ? t('dashboardSubtitle') : t('dashboardSubtitle'))}
                    </p>
                </div>
                <div className="flex gap-2">
                    <Button variant="outline" size="sm" className={`hidden sm:flex items-center gap-2 ${isAdmin ? 'border-green-500/50 text-green-500 hover:bg-green-500/10 hover:text-green-400 rounded-none bg-black' : ''}`}>
                        <Clock className="w-4 h-4" />
                        {isAdmin ? '[ TIME_RANGE ]' : t('dateRange')}
                    </Button>
                    <Button
                        size="sm"
                        className={`items-center gap-2 ${isAdmin ? 'bg-green-600 hover:bg-green-500 text-black font-bold rounded-none uppercase' : ''}`}
                        onClick={handleGenerateReport}
                        disabled={isGeneratingReport}
                    >
                        {isGeneratingReport ? (
                            <RefreshCw className="w-4 h-4 animate-spin" />
                        ) : (
                            <FileText className="w-4 h-4" />
                        )}
                        {isGeneratingReport ? (isAdmin ? "EXPORTING_DATA..." : "Generating...") : (isAdmin ? 'EXPORT_LOGS' : t('generateReport'))}
                    </Button>
                </div>
            </div>

            <div className="grid gap-4 md:grid-cols-2 md:gap-8 lg:grid-cols-4">
                <Card className={`hover:shadow-lg transition-all duration-200 group ${isAdmin ? 'bg-black/60 border border-green-500/30 rounded-none shadow-[0_0_10px_rgba(34,197,94,0.05)] text-green-500' : 'border-border/50 bg-white dark:bg-slate-950 shadow-sm'}`}>
                    <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                        <CardTitle className={`text-sm font-medium transition-colors ${isAdmin ? 'text-green-500/70 group-hover:text-green-400' : 'text-muted-foreground group-hover:text-primary'}`}>
                            {isAdmin ? 'CITIZEN_RECORDS' : t('citizens')}
                        </CardTitle>
                        <div className={`p-2 rounded-full transition-colors ${isAdmin ? 'bg-green-500/10 group-hover:bg-green-500/20' : 'bg-blue-50 dark:bg-blue-900/20 group-hover:bg-blue-100 dark:group-hover:bg-blue-900/40'}`}>
                            <Users className={`h-4 w-4 ${isAdmin ? 'text-green-500' : 'text-blue-600 dark:text-blue-400'}`} />
                        </div>
                    </CardHeader>
                    <CardContent>
                        <div className={`text-3xl font-bold ${isAdmin ? 'text-green-400' : 'text-primary'}`}>
                            {isLoading ? "..." : stats.citizens.toLocaleString()}
                        </div>
                        <p className={`text-xs mt-1 flex items-center gap-1 ${isAdmin ? 'text-green-600/70' : 'text-muted-foreground'}`}>
                            <TrendingUp className="w-3 h-3 text-green-500" />
                            <span className="text-green-500 font-medium">+2.5%</span> {isAdmin ? 'UP_SYS_AVG' : 'from last month'}
                        </p>
                    </CardContent>
                </Card>

                <Card className={`hover:shadow-lg transition-all duration-200 group ${isAdmin ? 'bg-black/60 border border-green-500/30 rounded-none shadow-[0_0_10px_rgba(34,197,94,0.05)] text-green-500' : 'border-border/50 bg-white dark:bg-slate-950 shadow-sm'}`}>
                    <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                        <CardTitle className={`text-sm font-medium transition-colors ${isAdmin ? 'text-green-500/70 group-hover:text-green-400' : 'text-muted-foreground group-hover:text-primary'}`}>
                            {isAdmin ? 'FAMILY_TREES_DB' : t('families')}
                        </CardTitle>
                        <div className={`p-2 rounded-full transition-colors ${isAdmin ? 'bg-green-500/10 group-hover:bg-green-500/20' : 'bg-indigo-50 dark:bg-indigo-900/20 group-hover:bg-indigo-100 dark:group-hover:bg-indigo-900/40'}`}>
                            <Home className={`h-4 w-4 ${isAdmin ? 'text-green-500' : 'text-indigo-600 dark:text-indigo-400'}`} />
                        </div>
                    </CardHeader>
                    <CardContent>
                        <div className={`text-3xl font-bold ${isAdmin ? 'text-green-400' : 'text-primary'}`}>
                            {isLoading ? "..." : stats.families.toLocaleString()}
                        </div>
                        <p className={`text-xs mt-1 flex items-center gap-1 ${isAdmin ? 'text-green-600/70' : 'text-muted-foreground'}`}>
                            <TrendingUp className="w-3 h-3 text-green-500" />
                            <span className="text-green-500 font-medium">+1.2%</span> {isAdmin ? 'UP_SYS_AVG' : 'from last month'}
                        </p>
                    </CardContent>
                </Card>

                <Card className={`hover:shadow-lg transition-all duration-200 group ${isAdmin ? 'bg-black/60 border border-green-500/30 rounded-none shadow-[0_0_10px_rgba(34,197,94,0.05)] text-green-500' : 'border-border/50 bg-white dark:bg-slate-950 shadow-sm'}`}>
                    <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                        <CardTitle className={`text-sm font-medium transition-colors ${isAdmin ? 'text-green-500/70 group-hover:text-green-400' : 'text-muted-foreground group-hover:text-primary'}`}>
                            {isAdmin ? 'SERVICES_DISPATCHED' : t('services')}
                        </CardTitle>
                        <div className={`p-2 rounded-full transition-colors ${isAdmin ? 'bg-green-500/10 group-hover:bg-green-500/20' : 'bg-orange-50 dark:bg-orange-900/20 group-hover:bg-orange-100 dark:group-hover:bg-orange-900/40'}`}>
                            <FileText className={`h-4 w-4 ${isAdmin ? 'text-green-500' : 'text-orange-600 dark:text-orange-400'}`} />
                        </div>
                    </CardHeader>
                    <CardContent>
                        <div className={`text-3xl font-bold ${isAdmin ? 'text-green-400' : 'text-primary'}`}>
                            {isLoading ? "..." : stats.servicesToday}
                        </div>
                        <p className={`text-xs mt-1 ${isAdmin ? 'text-green-600/70 uppercase' : 'text-muted-foreground'}`}>
                            {isAdmin ? 'ISSUED_LAST_24H' : 'Issued today'}
                        </p>
                    </CardContent>
                </Card>

                <Card className={`hover:shadow-lg transition-all duration-200 group ${isAdmin ? 'bg-black/60 border border-red-500/40 rounded-none shadow-[0_0_15px_rgba(239,68,68,0.1)] text-red-500' : 'border-border/50 bg-white dark:bg-slate-950 shadow-sm'}`}>
                    <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                        <CardTitle className={`text-sm font-medium transition-colors ${isAdmin ? 'text-red-500/80 group-hover:text-red-400' : 'text-muted-foreground group-hover:text-primary'}`}>
                            {isAdmin ? 'PENDING_ACTIONS_QUEUE' : t('pending')}
                        </CardTitle>
                        <div className={`p-2 rounded-full transition-colors ${isAdmin ? 'bg-red-500/10 group-hover:bg-red-500/20' : 'bg-red-50 dark:bg-red-900/20 group-hover:bg-red-100 dark:group-hover:bg-red-900/40'}`}>
                            <AlertCircle className={`h-4 w-4 ${isAdmin ? 'text-red-500' : 'text-red-600 dark:text-red-400'}`} />
                        </div>
                    </CardHeader>
                    <CardContent>
                        <div className={`text-3xl font-bold ${isAdmin ? 'text-red-500' : 'text-primary'}`}>
                            {isLoading ? "..." : stats.pending}
                        </div>
                        <p className={`text-xs mt-1 ${isAdmin ? 'text-red-500/70 uppercase font-bold' : 'text-muted-foreground'}`}>
                            {isAdmin ? 'WARNING: QUEUED_JOBS' : 'Requires action'}
                        </p>
                    </CardContent>
                </Card>
            </div>
        </main>
    );
}
